telegram:
  api-key: 6665204650:AAH81vmiVE2YvnD7GWhw8vMP7SbAgj5E8II
stickers:
  gachi: [ CAACAgIAAxkBAQABIH9lWID-QXtu1H0ldClCmKymWnQOdwACbxYAAg2pAUj2ZN0NwJMQIDME,
           CAACAgIAAxkBAQABIINlWIEExMv0QYgQ6vJsWpsQ35KS2QACNRIAAlbWCUhVwiQqqj_qfjME,
           CAACAgIAAxkBAQABIIdlWIEGDdSq88PmI0fF9ZM25WxKQwACdxIAArKbIUgiyytZj9BQ-DME,
           CAACAgIAAxkBAQABIItlWIEIgXJzihvq64nNar8fGID7VAACzBoAAk04gEvdN4O2JD6G5jME,
           CAACAgIAAxkBAQABII1lWIEJ_-2ZvwES2GUUcKAyhSpZxAACfRYAAjD2AAFIF55WEWUPI0szBA,
           CAACAgIAAxkBAQABII9lWIEKoUeiM4qz_KuB6Llt77csEQACUhMAAkSLAAFIc7Llet9uhRwzBA,
           CAACAgIAAxkBAQABIJVlWIEM9g4u3B9GDW7-A3dSwx8U9QACARUAAt3OAAFIk21Dnzg4I_MzBA,
           CAACAgIAAxkBAQABIJdlWIENolDuRa7JVBTDowFeaHUqdwAC6RIAAm09wEl8Ml_HBWexFTME,
           CAACAgIAAxkBAQABIJtlWIEPA0FGNjSdUrKq6LHs0b4P3AACRhcAAtPlAUi8Q4Yiot-rCjME,
           CAACAgIAAxkBAQABIKFlWIESjkDSqn7VmqY6duUO5lpgXQACaBkAAuy6AAFIUpaMcAAB5dCmMwQ,
           CAACAgIAAxkBAQABIKhlWIEWRalyd1jVyBhF70SD3nqbXQAC8BAAAtNBCUjVLuIs6NfDgDME,
           CAACAgIAAxkBAQABIK5lWIEaU_BbC7kP4Ee0MDaBnSAVpgAC7xQAAp7iAAFIbXupWhoLg7MzBA,
           CAACAgIAAxkBAQABILNlWIEgjfg9V5NgIm3KHJyKnFoP1gACvRQAAu1JAAFI0fInN5SrEEczBA,
           CAACAgIAAxkBAQABILdlWIEjEQ8PULDexVoxXj2cj42rOQACsRUAAv3nAUhwnO2Q-N-6zDME,
           CAACAgIAAxkBAQABILllWIEk55nxgALdxOh7E72YDczG_AACMxQAAmZkAAFIUR6qoi6ATUIzBA,
           CAACAgIAAxkBAQABIL5lWIEnrXbasBuwPQNmO8LWPbybBwACIRUAAv2yCEgmD1pj7SLoNTME,
           CAACAgIAAxkBAQABIMVlWIEsMcamyvv1ThKR003DcZlgxQACPBgAAuBwGUitbvj9Z4vJWDME,
           CAACAgIAAxkBAQABIMllWIEvcLYBt7psrRo11Dc1PuvWkgAChRwAAicPgEt74MNvvidN2DME,
           CAACAgIAAxkBAQABIM1lWIEx3wfTWnGSS8_ji-FB_X0DxQAClxcAAuEEAAFIhETc3t77qIQzBA,
           CAACAgIAAxkBAQABIM9lWIEyMg5zFFZ_UlsFT6O9hMIKuwACYxUAAlOHIUi8IImUvW83YTME,
           CAACAgIAAxkBAQABINhlWIFGJUFfpkR_jlntuUTjCJuV7gACDxUAAs9qGEiRzowKJ2uajzME,
           CAACAgIAAxkBAQABINtlWIFHNkJUDVmuiL50bM-BQ7ni8gACyBYAAj5LIUiO-uRl2gABneQzBA,
           CAACAgIAAxkBAQABIOBlWIFK2eqWqYzQzrugZlndfsTt1QACZBQAAjQwIUjiMtSYvTg4yzME,
           CAACAgIAAxkBAQABIOJlWIFLUQJEXTWc_xkbEYKkYJnQbwACWhQAAustGEjNK9gaDpXLQjME,
           CAACAgIAAxkBAQABIORlWIFMFlm9OVep6Wsjf6vleB8Z0wACWhMAApa7IUh7XykhK9pLODME,
           CAACAgIAAxkBAQABIOxlWIFRJjby5dC7tz3PiU1OaqAbMQACBhMAAlI8IUi0j4QzFokO2DME,
           CAACAgIAAxkBAQABIO9lWIFSHV-FB-OYPCvptFV2Kcm8AgADFgACCBQYSM6OTIUYpwpZMwQ,
           CAACAgIAAxkBAQABIPNlWIFT7Mwqf80-Ewz-UCw5MApFNAACGhcAAoCBIEgyFrIa5zZmyjME,
           CAACAgIAAxkBAQABIPxlWIFdG2z_-fNB9FA5pVrUNSifSQACGRUAAgGLGEiBStWojsPrbTME,
           CAACAgIAAxkBAQABIQABZViBXxTE1USsKWix1tnlgBb-z8QAAq4UAALCuRhI_s2h-30Z9fszBA,
           CAACAgIAAxkBAQABIQRlWIFh8Vi-XeAbY4OIGGYTZMH8-wACGBEAAgs8IUgY2JT6wqQRnjME,
           CAACAgIAAxkBAQABIQhlWIFj2JSyvGDtMSbt36k_uwsqAANOFAAC6HkgSBRO61qtDwW5MwQ,
           CAACAgIAAxkBAQABIQtlWIFkgqgh_0aIlqPBo0VPYZK6twACwRIAAtxQIEioXkYGa-hYxjME,
           CAACAgIAAxkBAQABIRllWIGKjgxg0VWyXqpt8r23iHprVgACLRYAAqpfyUvqsdo8dCAEIzME,
           CAACAgIAAxkBAQABIRplWIGLr7aUafmy2sDrBCT7Yu_OXwACERQAAg59yEugoW5wtcva3jME,
           CAACAgIAAxkBAQABISFlWIGSfTyQhafZPzxGWxy2m_ClTQACuxIAAkciyEuZfOib-BzJ1DME,
           CAACAgIAAxkBAQABISllWIGZn6NIUeA0knSiIdOeKd2NbQAC8xAAAnt4yUv8CBg5xaTu4DME,
           CAACAgIAAxkBAQABIS5lWIGd-GE3fX3lXLS-bDhiTkWGEwACmBUAAmIkyEvSG3uXKvKUOzME,
           CAACAgIAAxkBAQABITNlWIGoy325Z6g9BOQGRFQE8y7O7wACRhYAApVPyUt1xp2x3W7f3DME,
           CAACAgIAAxkBAQABITdlWIGrw9SVUCbvLJCRFR-4RjAY3AACBxEAAtNXyUuy0BOzu-EhMTME,
           CAACAgIAAxkBAQABITtlWIGuyOcyj53Yby045uJR-5j3XQAC6BMAAmKByEtvfziK0AuXeDME,
           CAACAgIAAxkBAQABIUFlWIGyrkRy03kr49Q1LnFGIX2EcwACDxEAAojF0Usu_WLHr8VjzjME,
           CAACAgIAAxkBAQABIVBlWIHfRXWe4S_2zRc5NLcMKVvd8wACJhMAAiwoyEsj7vCNLNXTijME,
           CAACAgIAAxkBAQABIVZlWIHloP-pYv73Szjcfor2DARzoQACYBgAApQWyEsAAaJw9UjZQRUzBA,
           CAACAgIAAxkBAQABIVhlWIHnHP9PMDSe1USjDxG3Frn33gACKBcAAgbygErCTNkBu8AvAzME,
           CAACAgIAAxkBAQABIWdlWIH9J8gB8PKz7YXVk3bp5QNXbwAC3QADZj9IJpsPxROmD7yuMwQ,
           CAACAgIAAxkBAQABIXhlWIIaXfOIJzQaMjYgylZbuPRHyAACCgAD2WCVGG5FE5KcqBKbMwQ,
           CAACAgIAAxkBAQABIXxlWIIez-53DUEvmg-8t9XjrTyNdAACPAAD2WCVGH2FfshJXqUxMwQ]
replies:
  kirill: Кирилл, на тебе стикер, что ли